### ISSUE TITLE
working time schedule

### ISSUE THREAD

**Issue by pepeverde9** [breuerfelix/king-bot-api#56]
Hi
I do not trust the bot to run 24/7. If there is anybody halfway attentive to what is going on in the game, he will know that a bot is playing.
I am running the bot by a bash script with timeout and sleep on a raspberry pi, so it's not a real issue for me, but it would be nice to have the working time schedule in the bot.

**Comment by OneManDevz** [comment]
I think you can set it up by yourself. 
In task scheduler you can start a node script to start the bot, etc..
Something like this. 
is this suitable workaround, @fbreuer94 ?
![image](https://user-images.githubusercontent.com/42937562/56964035-a4587500-6b5a-11e9-9005-45c39e5bcfb6.png)

**Comment by breuerfelix** [comment]
@OneManDevz yeah that's the windows version of a cron job with a bash script on a raspberry pi :)

@pepeverde9 that feature would also be good for night mode servers BUT I think there would be way more important features to implement first like your trading by percentage feature or dodge incoming attacks, so I will close this one since its hard to implement right now, your solution is by far the easiest approach for that :)
