### ISSUE TITLE
Use of village ID or village coordinates instead of village name in the code base

### ISSUE THREAD

**Issue by raj-aayush** [breuerfelix/king-bot-api#58]
The current bot uses the village name when referring to tasks assigned to a certain village. This means that the bot will break under the following conditions:
* A village name changes
* Multiple villages (of the same player) share the same name

I think we can refactor the code to ensure that village ID is used (which stays constant and is unique) instead of village name to avoid such issues.

**Comment by breuerfelix** [comment]
really good idea ! why did I choose the village name ?

easy to answer, back then I had no gui for the players so the user had to manually insert the village identifier in order to farm in that village.

and for the player to get the village ID he has to scan his network traffic :D so I thought okay he enters the village name and I try to get the correct village from that.

but since we got the gui now... this idea is awesome ! I can add you to the contributors so you can make a branch here in this repo if you want to :) just let me know !

**Comment by raj-aayush** [comment]
Aah I see. That explains the functionality. I'm already working on refactoring the village.find() function. I can push it to a separate branch as soon as I'm done with it. Adding me to the contributors list would be very useful and I would really appreciate it.

**Comment by raj-aayush** [comment]
Bug fix implemented. Refer[https://github.com/breuerfelix/king-bot-api/commit/b3232ae195806480255039e814f5afb55fb73e31](url)

**Comment by breuerfelix** [comment]
hey mate, thanks for the refactor !!

just a small annotation, if you fix something next time, it would be cool if you could make a new branch and make a pull request with your changes :)

that way its easier to see what has changes each commit :)

**Comment by raj-aayush** [comment]
Yeah for sure! I'll keep that in mind. Thanks for the heads up, buddy!
