### ISSUE TITLE
Docker version keep restarting

### ISSUE THREAD

**Issue by aklimzzh** [breuerfelix/king-bot-api#96]
Latest version
ARM CPU
OpenMediaVault
Docker CE

keep restarting
log
`standard_init_linux.go:211: exec user process caused "exec format error"
`

**Comment by aklimzzh** [comment]
more info

Distributor ID: Debian
Description:    Debian GNU/Linux 9 (stretch)
Release:        9
Codename:       stretch

Docker version 19.03.5, build 633a0ea

**Comment by breuerfelix** [comment]
you have to use the :rpi tag because you are running on an ARM processor.

the ARM build is NOT up to date! if you want an up to date docker build you have to use the rpi.Dockerfile and do a rebuild on your own (because in dockerhub you cannot run automated ARM builds)

a little hint: do not add restart=always if you run the container for the first time.  
travian added a new feature which bans your account when attempting a login which is not successfull (some times in a row) so first try your cred.txt to be 100% correct. Otherwhise you have to contact the support really quickly because the account gets locked for security reasons.

**Comment by aklimzzh** [comment]
got it, thanks for the answer
